'use client';
import Link from 'next/link';
import {useState} from 'react';

export const copy={
 en:{home:'Home',quote:'AI Quote',upload:'Upload Documents',tracking:'Tracking',chat:'AI Customs Chatbot',contact:'Contact',email:'tim@jomainc.com',heroTitle:'AI-Powered Freight, Customs & Logistics Solutions',heroText:'Joma Logistics Incorporated helps importers manage international freight, U.S. customs clearance, trucking, warehousing and shipment documents with AI-assisted logistics workflows.',getQuote:'Get AI Freight Quote',uploadDocs:'Upload Shipment Documents',askAI:'Ask AI Assistant',services:'Integrated Logistics Services',servicesSub:'Modern freight forwarding and customs support for importers, e-commerce sellers and supply chain teams.',aiTitle:'AI Logistics Operating System',aiText:'A Flexport-style digital workflow for quotes, documents, duty estimates, customs review and shipment visibility.',footer:'AI-powered logistics, customs, trucking and delivery solutions.'},
 zh:{home:'首页',quote:'AI 报价',upload:'上传文件',tracking:'货物追踪',chat:'AI 清关助手',contact:'联系我们',email:'tim@jomainc.com',heroTitle:'AI 智能国际物流、清关与派送解决方案',heroText:'Joma Logistics Incorporated 帮助进口商通过 AI 工作流处理国际运输、美国清关、拖车派送、仓储、单证审核与货物追踪。',getQuote:'获取 AI 运费报价',uploadDocs:'上传物流文件',askAI:'咨询 AI 助手',services:'一体化物流服务',servicesSub:'为进口商、电商卖家和供应链团队提供现代化货运代理与清关支持。',aiTitle:'AI 物流操作系统',aiText:'类似 Flexport 风格的数字化工作流：报价、文件、关税预估、清关审核和货物可视化。',footer:'AI 智能物流、美国清关、拖车派送和到门解决方案。'}
};
export function useLang(){const [lang,setLang]=useState('en');return {lang,setLang,t:copy[lang]}}
export function Header({lang,setLang,t}){return <><div className="topbar"><span>Joma Logistics Incorporated</span><span>Website: www.jomainc.com · Email: {t.email}</span></div><header className="navbar"><Link href="/" className="brand"><span className="logo">J</span><span>JOMA LOGISTICS</span></Link><nav className="navlinks"><Link href="/">{t.home}</Link><Link href="/#quote">{t.quote}</Link><Link href="/upload-documents">{t.upload}</Link><Link href="/tracking">{t.tracking}</Link><Link href="/ai-customs-chatbot">{t.chat}</Link><Link href="/contact">{t.contact}</Link></nav><button className="langbtn" onClick={()=>setLang(lang==='en'?'zh':'en')}>{lang==='en'?'中文':'English'}</button></header></>}
export function Footer({t}){return <footer className="footer"><div><h3>Joma Logistics Incorporated</h3><p>{t.footer}</p><p>www.jomainc.com</p></div><div><h3>Contact</h3><p>Email: tim@jomainc.com</p><p>Chicago · United States</p></div><div><h3>Core Services</h3><p>Ocean Freight · Air Freight · Customs Clearance · Trucking · DDP</p></div></footer>}
export function Shell({children}){const {lang,setLang,t}=useLang();return <><Header lang={lang} setLang={setLang} t={t}/>{children(t,lang)}<Footer t={t}/></>}
